#! /bin/bash

# fix resolvconf: signature mismatch
if ! grep -q "^# Generated by resolvconf" /etc/resolv.conf; then
    sed -i "1s/^/# Generated by resolvconf\n/" /etc/resolv.conf
fi

# create /dev/net/tun if it does not exist
if [[ ! -c /dev/net/tun ]]; then
    mkdir -p /dev/net && mknod /dev/net/tun c 10 200
fi
